sc delete PG_AccDB
sc delete PG_ALDB
sc delete PG_W00_CDB
sc delete PG_W00_GLDB
sc delete PG_Login
sc delete PG_W00_WM
sc delete _GamigoZR
sc delete PG_W00_Z00
sc delete PG_W00_Z01
sc delete PG_W00_Z02
sc delete PG_W00_Z03
sc delete PG_W00_Z04
sc delete Account
sc delete AccountLog
sc delete Character
sc delete GameLog
sc delete Login
sc delete WorldManager
sc delete _GamigoZR
sc delete Zone0
sc delete Zone1
sc delete Zone2
sc delete Zone3
sc delete Zone4